name: Deploy CRM to Atalaya

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Pulling and migrating CRM into Atalaya
        env:
          SSH_HOST: atalaya.pe
          SSH_USER: root
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST << 'EOF'
            cd /var/www/crm
            git pull
            php artisan migrate --force
            php artisan config:clear
            php artisan cache:clear
          EOF